### ISSUE TITLE
Missing error messages near search field when some domain is already opened

### ISSUE THREAD

**Issue by ProgramCrafter** [ton-blockchain/dns#14]
### Bug Type

UI

### Reproduction steps

1. Open any domain (e.g. `aaaaa.ton`)
2. Enter other name, **too short for domain** (for example, `aaa.ton`), in search field.
3. Press `Enter` to search this domain.

### Actual result

The page does not do anything in response to invalid domain name.

**As well, if I go back to main page (https://dns.ton.org/#) by clicking TON logo, the error message is shown, but invalid domain name being checked (`aaa.ton`) isn't visible. That can possibly confuse users.**

### Expected result

The page shows an error message that domain name is too short.
When returning to the main page, either error message should disappear, or attempted domain name should be shown.

### Suggested Severity

Medium

### Device

Desktop:
- OS: Windows 10
- Browser: Firefox
- Version: 94.0

### Additional Context

Partially related to #9.
However, this issue has a part not mentioned before - about error message shown on the main page.

**Comment by DulkarnaevNail** [comment]
I want to supplement the information in this bug.  This problem is repeated in the Opera browser(Version 91.0.4516.16). This problem is not observed in the Chrome browser(Version 105.0.5195.125).

**Comment by EmelyanenkoK** [comment]
Duplicates https://github.com/ton-blockchain/dns/issues/9 (as I can see info about error message on main page is presented in #9 as well)
