### ISSUE TITLE
Missing invalid domain warning

### ISSUE THREAD

**Issue by isopen** [ton-blockchain/dns#15]
### Bug Type

UI/UX

### Reproduction steps

![Снимок экрана от 2022-09-21 06-13-37](https://user-images.githubusercontent.com/7373292/191380890-8927ea6e-5d1f-4270-b075-47c12a7ed40b.png)

### Actual result

1. Ввести в строке поиска -testertesterov
2. Нажать Enter
3. Домен не валиден. Предупреждения нет.

### Expected result

Создать предупреждение. Alert, если по другому никак (можно переиспользовать с главного экрана).

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: Ubuntu 22
- Browser Google Chrome
- Version 105.0.5195.52

**Comment by EmelyanenkoK** [comment]
Duplicates #9
