### ISSUE TITLE
Inappropriate domain price

### ISSUE THREAD

**Issue by isopen** [ton-blockchain/dns#16]
### Bug Type

Functional

### Reproduction steps

![image](https://user-images.githubusercontent.com/7373292/191382600-2272436d-b1a6-4243-8f05-6c3b10a4b673.png)

### Actual result

Current result 90 TON

### Expected result

Most likely the price is not more than 9 TON.
Check the price distribution algorithm for suitability.
<img src="https://user-images.githubusercontent.com/7373292/191383046-98380511-b4f9-4871-8bf5-fac1725d20d2.png" width="50%" />

### Suggested Severity

Critical

### Device

ALL DEVICES

**Comment by ProgramCrafter** [comment]
> Most likely the price is not more than 9 TON.

As far as I know, the price depends on domain name length - the shorter, the cheaper.

**Comment by isopen** [comment]
@ProgramCrafter Maybe even start on the weight of the word for the user?

**Comment by EmelyanenkoK** [comment]
Works as intended.
