### ISSUE TITLE
No warning message for domain if string length less than 4 items

### ISSUE THREAD

**Issue by ArteSK88** [ton-blockchain/dns#19]
### Bug Type

Functional

### Reproduction steps

1. Enter https://dns.ton.org/#
2. Input any valid data (len(str) >= 4) in 'Enter a domain to start' field
3. Press enter
4. Input any value from Test data in the text field in the upper right part of the page
5. Press enter

Test data:
a
ab
abc
1ab
12
123

https://user-images.githubusercontent.com/108936297/191998476-1062a84e-9960-431c-a36b-6542d4dc5c5c.mp4

### Actual result

Nothing happens

### Expected result

A notice appears to inform a user of an appropriate input format

### Suggested Severity

Medium

### Device

Desktop:

- OS: Windows 10 64-bit
- Browser: Chrome
- Version 105.0.5195.12

**Comment by EmelyanenkoK** [comment]
Duplicated #9
